News/urls.py
from django.urls import path

from News import views

app_name = 'news'

urlpatterns = [
    path('list', views.AllNews.as_view(), name='all'),
    path('detail/<slug>', views.NewsDetail.as_view(), name='detail'),
    path('category/<slug>', views.NewsByCategory.as_view(), name='by_category'),
]

SharifMBI/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from SharifMBI import settings

urlpatterns = ([
                   path("", include("Home.urls")),
                   path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
                   path('ratings/', include("star_ratings.urls", namespace="ratings")),
                   path('hitcount/', include("hitcount.urls", namespace="hitcount")),
                   path("i18n/", include("django.conf.urls.i18n")),
                   path("account/", include("Account.urls")),
                   path("us/", include("Us.urls")),
                   path("weblog/", include("Weblog.urls")),
                   path("news/", include("News.urls")),
                   path("diagnose/", include("Diagnose.urls")),
               ] +
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

Us/urls.py
from django.urls import path

from Us import views

app_name = 'us'

urlpatterns = [
    path('about', views.About.as_view(), name='about'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('customers', views.CustomerList.as_view(), name='customers'),
    path('customer/<slug>', views.CustomerDetail.as_view(), name='customer'),
    path('faq/detail/<slug>', views.FaqDetail.as_view(), name='faq'),
    path('faqs', views.FaqList.as_view(), name='faqs'),
]

News/models.py
from itertools import chain

from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models import Count
from django_ckeditor_5.fields import CKEditor5Field
from django_jalali.db.models import jDateTimeField
from hitcount.models import HitCount
from star_ratings.models import Rating


class Tag(models.Model):
    name = models.CharField(max_length=75, unique=True, verbose_name='نام')

    slug = models.SlugField(unique=True, allow_unicode=True, verbose_name='اسلاگ')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'news__tags'
        verbose_name = 'تگ'
        verbose_name_plural = 'تگ‌ها'


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='نام')

    slug = models.SlugField(unique=True, allow_unicode=True, verbose_name='اسلاگ')

    icon = models.ImageField(upload_to='News/Category/icons/', verbose_name='آیکون', blank=True, null=True)

    cover_image = models.ImageField(upload_to='News/Category/images', verbose_name='تصویر', blank=True, null=True)

    description = CKEditor5Field(config_name="extends", verbose_name='درباره دسته بندی')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'news__category'
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی‌ها'


class News(models.Model):
    author = models.ForeignKey(to="Account.CustomUser", on_delete=models.CASCADE, verbose_name='نویسنده',
                               editable=False, related_name='news')

    title = models.CharField(max_length=100, verbose_name='عنوان')

    slug = models.SlugField(unique=True, allow_unicode=True, verbose_name='اسلاگ')

    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='دسته بندی')

    tags = models.ManyToManyField(to=Tag, verbose_name='تگ‌ها', blank=True, related_name='news')

    content = CKEditor5Field(config_name="extends", verbose_name="محتوا")

    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')

    ratings = GenericRelation(to=Rating, related_query_name='news')

    cover_image = models.ImageField(upload_to='News/News/cover_images', verbose_name='تصویر کاور')

    created_at = jDateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')

    updated_at = jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین به‌روز‌رسانی')

    def get_related_news(self, max_results=5):
        """
        Returns related news based on shared tags and categories, ranked by shared tags and then publication date.
        """

        related_news = (
            News.objects.filter(tags__in=self.tags.all())
            .exclude(id=self.id)  # Exclude the current new
            .annotate(tag_count=Count('tags'))  # Count shared tags
            .order_by('-tag_count', '-created_at')  # Rank by shared tags, then date
        )

        # If not enough results from tags, try categories:
        if related_news.count() < max_results:
            category_news = News.objects.filter(category=self.category)
            category_news = category_news.exclude(id=self.id)  # Exclude the current new
            category_news = category_news.order_by('-created_at')[:max_results - related_news.count()]
            related_news = list(chain(related_news, category_news))  # Convert to list

        return list(set(related_news))[:max_results]  # Ensure related_news is a list before slicing

    def get_latest_news(self):
        latest_news = News.objects.all().order_by('-created_at')

        return latest_news

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = 'news__news'
        verbose_name = 'خبر'
        verbose_name_plural = 'اخبار'

News/views.py
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, get_list_or_404
from django.utils.encoding import uri_to_iri
from django.views.generic import ListView, DetailView
from hitcount.views import HitCountDetailView

from Home.mixins import URLStorageMixin
from News.models import News, Category


class AllNews(URLStorageMixin, ListView):
    model = News
    context_object_name = 'news'
    template_name = 'News/news_list.html'
    paginate_by = 9

    def get_queryset(self):
        news = News.objects.select_related('category', 'author').order_by('-created_at')

        return news

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = Category.objects.all()

        context['categories'] = categories

        print(categories)

        return context


class NewsDetail(URLStorageMixin, HitCountDetailView, DetailView):
    model = News
    context_object_name = 'news'
    template_name = 'News/news_detail.html'
    count_hit = True

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.select_related('category', 'author')

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)

            related_news = self.object.get_related_news(max_results=3)
            latest_news = self.object.get_latest_news()

            context['related_news'] = related_news
            context['latest_news'] = latest_news

            return context

        except IntegrityError:
            pass

    def get_object(self, queryset=None):
        slug = uri_to_iri(self.kwargs.get(self.slug_url_kwarg))
        queryset = self.get_queryset()
        return get_object_or_404(queryset, **{self.slug_field: slug})


class NewsByCategory(URLStorageMixin, ListView):
    model = News
    context_object_name = 'news'
    template_name = 'News/news_by_category.html'
    paginate_by = 9

    def get_queryset(self):
        slug = uri_to_iri(self.kwargs.get('slug'))

        news = get_list_or_404(News, category__slug=slug)

        return news

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        slug = self.kwargs.get('slug')

        category = Category.objects.get(slug=slug)

        context['category'] = category

        return context

News/templates/News/news_by_category.html
{% extends 'base.html' %}
{% load filters %}
{% load static %}

{% block content %}
    <!--main content wrapper start-->
    <div class="main-wrapper">

        {% include 'includes/header.html' %}

        <!--page header section start-->
        <section class="page-header position-relative overflow-hidden ptb-120 bg-dark"
                 style="background: url('assets/img/page-header-bg.svg')no-repeat center bottom">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-md-12">
                        <div class="section-heading text-center">
                            <h1 class="display-5 fw-bold">دسته بندی {{ category }} عارضه یابی شریف</h1>
                            <p class="lead mb-0">{{ category.description|safe }}</p>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center text-center">
                    <div class="col-xl-8">

                        {% for category in categories %}
                            <a href="{% url 'news:by_category' category.slug %}"
                               class="btn btn-soft-primary btn-pill btn-sm m-2">{{ category.name }}</a>
                        {% endfor %}

                    </div>
                </div>
                <div class="bg-circle rounded-circle circle-shape-3 position-absolute bg-dark-light left-5"></div>
            </div>
        </section>
        <!--page header section end-->

        <!--blog section start-->
        <section class="masonary-blog-section ptb-120">
            <div class="container">

                <div class="row">

                    {% for news in news %}
                        <div class="col-lg-4 col-md-6">
                            <div class="single-article rounded-custom my-3">
                                <a href="{% url 'news:detail' news.slug %}" class="article-img">
                                    <img src="{{ news.cover_image.url }}" alt="article" class="img-fluid">
                                </a>
                                <div class="article-content p-4">
                                    <a href="{% url 'news:detail' news.slug %}">
                                        <h2 class="h5 article-title limit-2-line-text">{{ news.title }}</h2>
                                    </a>
                                    <p class="limit-2-line-text">{{ news.content|safe|truncatechars:75 }}</p>
                                    <div class="d-flex align-items-center pt-4">
                                        {% if news.author.image %}
                                            <div class="avatar">
                                                <img src="{{ news.author.image }}" alt="avatar" width="40"
                                                     class="img-fluid rounded-circle me-3">
                                            </div>
                                        {% else %}
                                            <div class="avatar">
                                                <img src="{% static 'img/author.JPG' %}" alt="avatar" width="40"
                                                     class="img-fluid rounded-circle me-3">
                                            </div>
                                        {% endif %}
                                        <div class="avatar-info">
                                            <h6 class="mb-0 avatar-name">{{ news.author.full_name }}</h6>
                                            <span class="small fw-medium text-muted">{{ news.created_at|j_date_formatter }}</span>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                <div class="row justify-content-center align-items-center mt-5">
                    <div class="col-auto my-1">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}"
                               class="btn btn-soft-primary btn-sm">قبلي</a>
                        {% else %}
                            <a href="#" class="btn btn-soft-primary btn-sm disabled">قبلي</a>
                        {% endif %}
                    </div>
                    <div class="col-auto my-1">
                        <nav>
                            <ul class="pagination rounded mb-0">
                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                    <div class="col-auto my-1">
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-soft-primary btn-sm">بعدي</a>
                        {% else %}
                            <a href="#" class="btn btn-soft-primary btn-sm disabled">بعدي</a>
                        {% endif %}
                    </div>
                </div>

            </div>
        </section>
        <!--blog section end-->
        {% include 'includes/footer.html' %}
    </div>
    <!--main content wrapper ends-->
{% endblock %}

News/templates/News/news_detail.html
{% extends 'base.html' %}
{% load ratings %}
{% load filters %}
{% load static %}
{% load hitcount_tags %}

{% block content %}

    <!--main content wrapper start-->
    <div class="main-wrapper">

        {% include 'includes/header.html' %}

        <!--page header section start-->
        <section class="page-header position-relative overflow-hidden ptb-120 bg-dark"
                 style="background: url('assets/img/page-header-bg.svg')no-repeat bottom right">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-8 col-12">
                        <h1 class="fw-bold display-5">{{ news.title }}</h1>
                    </div>
                </div>
                <div class="bg-circle rounded-circle circle-shape-3 position-absolute bg-dark-light left-5"></div>
            </div>
        </section>
        <!--page header section end-->

        <!--blog details section start-->
        <section class="blog-details ptb-120">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-lg-8 pe-5">
                        <div class="blog-details-wrap">
                            <img src="{{ news.cover_image.url }}" class="img-fluid mt-4 rounded-custom"
                                 alt="apply">
                            <div class="job-details-info mt-5">
                                {{ news.content|safe }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="author-wrap text-center bg-light p-5 sticky-sidebar rounded-custom mt-5 mt-lg-0">
                            <div class="blog-single-rating-post slider-parent-2">
                                <h6 class="h5">این وبلاگ چقدر براتون مفید بود؟</h6>
                                <br>
                                <div>
                                    {% ratings news %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--blog details section end-->

        <!--related blog start-->
        <section class="related-blog-list ptb-120 bg-light">
            <div class="container">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-4 col-md-12">
                        <div class="section-heading">
                            <h4 class="h5 text-primary">اخبار مشابه <h2 class="text-primary">عارضه یابی شریف</h2>
                            </h4>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-12">
                        <div class="text-start text-lg-end mb-4 mb-lg-0 mb-xl-0">
                            <a href="{% url 'news:all' %}" class="btn btn-primary">مشاهده همه اخبار</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for news in related_news %}
                        <div class="col-lg-4 col-md-6">
                            <div class="single-article rounded-custom mb-4 mb-lg-0">
                                <a href="{% url 'news:detail' news.slug %}" class="article-img">
                                    <img src="{{ news.cover_image.url }}" alt="article" class="img-fluid">
                                </a>
                                <div class="article-content p-4">
                                    <a href="{% url 'news:detail' news.slug %}">
                                        <h2 class="h5 article-title limit-2-line-text">{{ news.title }}</h2>
                                    </a>
                                    <p class="limit-2-line-text">{{ news.content|safe|truncatechars:75 }}</p>

                                    <div class="d-flex align-items-center pt-4">
                                        {% if news.author.image %}
                                            <div class="avatar">
                                                <img src="{% static "img/testimonial/6.jpg" %}" alt="avatar" width="40"
                                                     class="img-fluid rounded-circle me-3">
                                            </div>
                                        {% else %}
                                            <div class="avatar">
                                                <img src="{% static "img/author.JPG" %}" alt="avatar" width="40"
                                                     class="img-fluid rounded-circle me-3">
                                            </div>
                                        {% endif %}
                                        <div class="avatar-info">
                                            <h6 class="mb-0 avatar-name">{{ news.author.full_name }}</h6>
                                            <span class="small fw-medium text-muted">{{ news.created_at|j_date_formatter }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!--related blog end-->

        {% include 'includes/footer.html' %}

    </div>
    <!--main content wrapper end-->


{% endblock %}

News/templates/News/news_list.html
{% extends 'base.html' %}
{% load filters %}
{% load hitcount_tags %}
{% load static %}

{% block content %}
    <!--main content wrapper start-->
    <div class="main-wrapper">

        {% include 'includes/header.html' %}

        <!--page header section start-->
        <section class="page-header position-relative overflow-hidden ptb-120 bg-dark"
                 style="background: url('assets/img/page-header-bg.svg')no-repeat center bottom">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-md-12">
                        <div class="section-heading text-center">
                            <h1 class="display-5 fw-bold">آخرین اخبار عارضه یابی شریف</h1>
                            <p class="lead mb-0">شما در این بخش امکان مشاهده تمام اخبار عارضه یابی شریف را خواهید
                                داشت.
                            </p>
                            <p>
                                همچنین با استفاده از دسته بندی‌های زیر، راحت‌تر به مقالات مورد نیاز خود دسترسی پیدا
                                کنید.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center text-center">
                    <div class="col-xl-8">

                        {% for category in categories %}
                            <a href="{% url 'news:by_category' category.slug %}"
                               class="btn btn-soft-primary btn-pill btn-sm m-2">{{ category.name }}</a>
                        {% endfor %}

                    </div>
                </div>
                <div class="bg-circle rounded-circle circle-shape-3 position-absolute bg-dark-light left-5"></div>
            </div>
        </section>
        <!--page header section end-->

        <!--blog section start-->
        <section class="masonary-blog-section ptb-120">
            <div class="container">

                <div class="row">

                    {% for news in news %}
                        <div class="col-lg-4 col-md-6">
                            <div class="single-article rounded-custom my-3">
                                <a href="{% url 'news:detail' news.slug %}" class="article-img">
                                    <img src="{{ news.cover_image.url }}" alt="article" class="img-fluid">
                                </a>
                                <div class="article-content p-4">
                                    <a href="{% url 'news:detail' news.slug %}">
                                        <h2 class="h5 article-title limit-2-line-text">{{ news.title }}</h2>
                                    </a>
                                    <p class="limit-2-line-text">{{ news.content|safe|truncatechars:75 }}</p>
                                    <p><i class="fas fa-eye"></i> {% get_hit_count for news %}</p>
                                    <div class="d-flex align-items-center pt-4">
                                        <div class="avatar-info">
                                            <h6 class="mb-0 avatar-name">{{ news.author.full_name }}</h6>
                                            <span class="small fw-medium text-muted">{{ news.created_at|j_date_formatter }}</span>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="row justify-content-center align-items-center mt-5">
                    <div class="col-auto my-1">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}"
                               class="btn btn-soft-primary btn-sm">قبلي</a>
                        {% else %}
                            <a href="#" class="btn btn-soft-primary btn-sm disabled">قبلي</a>
                        {% endif %}
                    </div>
                    <div class="col-auto my-1">
                        <nav>
                            <ul class="pagination rounded mb-0">
                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                    <div class="col-auto my-1">
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-soft-primary btn-sm">بعدي</a>
                        {% else %}
                            <a href="#" class="btn btn-soft-primary btn-sm disabled">بعدي</a>
                        {% endif %}
                    </div>
                </div>

            </div>
        </section>
        <!--blog section end-->
        {% include 'includes/footer.html' %}
    </div>
    <!--main content wrapper ends-->
{% endblock %}