Account/urls.py
from django.urls import path

from Account import views

app_name = "account"

urlpatterns = [
    path("login", views.LogInView.as_view(), name="login"),
    path("register", views.OTPRegisterView.as_view(), name="register"),
    path("logout", views.LogOutView.as_view(), name="logout"),
    path("check/otp", views.CheckOTPView.as_view(), name="check_otp"),
    path("password/forget", views.ForgetPasswordView.as_view(), name="forget_password"),
    path("password/change", views.ChangePasswordView.as_view(), name="change_password"),
    path("enter_newsletters", views.EnterNewsletters.as_view(), name="enter_newsletters"),
]

Home/urls.py
from django.urls import path

from Home import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

News/urls.py
from django.urls import path

from News import views

app_name = 'news'

urlpatterns = [
    path('list', views.AllNews.as_view(), name='all'),
    path('detail/<slug>', views.NewsDetail.as_view(), name='detail'),
    path('category/<slug>', views.NewsByCategory.as_view(), name='by_category'),
]

SharifMBI/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from SharifMBI import settings

urlpatterns = ([
                   path("", include("Home.urls")),
                   path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
                   path('ratings/', include("star_ratings.urls", namespace="ratings")),
                   path('hitcount/', include("hitcount.urls", namespace="hitcount")),
                   path("i18n/", include("django.conf.urls.i18n")),
                   path("account/", include("Account.urls")),
                   path("us/", include("Us.urls")),
                   path("weblog/", include("Weblog.urls")),
                   path("news/", include("News.urls")),
                   path("diagnose/", include("Diagnose.urls")),
               ] +
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

Us/urls.py
from django.urls import path

from Us import views

app_name = 'us'

urlpatterns = [
    path('about', views.About.as_view(), name='about'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('customers', views.CustomerList.as_view(), name='customers'),
    path('customer/<slug>', views.CustomerDetail.as_view(), name='customer'),
    path('faq/detail/<slug>', views.FaqDetail.as_view(), name='faq'),
    path('faqs', views.FaqList.as_view(), name='faqs'),
]

Weblog/urls.py
from django.urls import path

from Weblog import views

app_name = 'weblog'

urlpatterns = [
    path('list', views.AllWeblogs.as_view(), name='all'),
    path('detail/<slug>', views.WeblogDetail.as_view(), name='detail'),
    path('category/<slug>', views.WeblogsByCategory.as_view(), name='by_category'),
]

templates/includes/css_urls.html
{% load static %}

<!--favicon icon-->
<link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png" sizes="16x16">

<!--google fonts-->
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&amp;family=Open+Sans:wght@400;600&amp;display=swap"
      rel="stylesheet">

<!--build:css-->
<link rel="stylesheet" href="{% static 'css/main-rtl.css' %}">
<!-- endbuild -->

<!--custom css start-->
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<!--custom css end-->

<!--star-ratings start-->
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<!--custom css end-->

templates/includes/footer.html
{% load static %}

<!--footer section start-->
<footer class="footer-section">
    <!--footer top start-->
    <!--for light footer add .footer-light class and for dark footer add .bg-dark .text-white class-->
    <div class="footer-top footer-light ptb-120">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-4 mb-md-4 mb-lg-0">
                    <div class="footer-single-col">
                        <div class="footer-single-col mb-4">
                            <img src="{% static 'img/logo-white.png' %}" alt="logo" class="img-fluid logo-white">
                            <img width="80px" height="30px" src="{% static 'img/logo-dark.jpg' %}" alt="logo" class="img-fluid logo-color">
                        </div>
                        <p>آخرین اخبار، مقالات و منابع را در صندوق پستی شما هفتگی ارسال خواهیم کرد</p>

                        <form method="post" action="{% url 'account:enter_newsletters' %}"
                              class="newsletter-form position-relative d-block d-lg-flex d-md-flex">
                            {% csrf_token %}

                            <input type="email" name="email" value="" class="input-newsletter form-control me-2"
                                   placeholder="ایمیل خود را وارد کنید" required autocomplete="off">
                            <input type="submit" value="اشتراک" data-wait="صبر کنید ..."
                                   class="btn btn-primary mt-3 mt-lg-0 mt-md-0">
                        </form>
                    </div>
                </div>
                <div class="col-md-12 col-lg-7 mt-4 mt-md-0 mt-lg-0">
                    <div class="row">
                        <div class="col-md-4 col-lg-4 mt-4 mt-md-0 mt-lg-0">
                            <div class="footer-single-col">
                                <h3>صفحات اصلی</h3>
                                <ul class="list-unstyled footer-nav-list mb-lg-0">
                                    <li><a href="{% url 'home:home' %}" class="text-decoration-none">خانه</a></li>
                                    <li><a href="{% url 'diagnose:form' %}" class="text-decoration-none">فرم عارضه
                                        یابی</a></li>
                                    <li><a href="{% url 'weblog:all' %}" class="text-decoration-none">وبلاگ‌ها</a></li>
                                    <li><a href="{% url 'news:all' %}" class="text-decoration-none">اخبار</a></li>
                                    <li><a href="{% url 'us:about' %}" class="text-decoration-none">درباره ما</a></li>
                                    <li><a href="{% url 'us:contact' %}" class="text-decoration-none">ارتباط با ما</a>
                                    <li><a href="{% url 'us:faqs' %}" class="text-decoration-none">سوالات متداول</a>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4 mt-4 mt-md-0 mt-lg-0">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d809.9515298546016!2d51.3488396!3d35.7063884!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8e00a98a1ad941%3A0x14d5da317115e0a8!2z2YXYsdqp2LIg2KLZhdmI2LLYtCDZhdmH2KfYsdiqINmH2KfbjCDZvtuM2LTYsdmB2KrZhyDYtdmG2LnYqtuMINi02LHbjNmB!5e0!3m2!1sen!2s!4v1712481299525!5m2!1sen!2s"
                                    height="390" width="390" style="border-radius:10px;" allowfullscreen=""
                                    loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--footer top end-->

    <!--footer bottom start-->
    <div class="footer-bottom footer-light py-4">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-md-7 col-lg-7">
                </div>
                <div class="col-md-4 col-lg-4">
                    <div class="footer-single-col text-start text-lg-end text-md-end">
                        <ul class="list-unstyled list-inline footer-social-list mb-0">
                            {% if social_media.whats_App_icon %}
                                <li class="list-inline-item">
                                    <a href="{{ social_media.whats_App_url }}"> <img
                                            src="{{ social_media.whats_App_icon.url }}" height="18px" width="18px"
                                            alt=""
                                            style="padding-bottom: 5px;">
                                    </a>
                                </li>
                            {% endif %}

                            {% if social_media.telegram_icon %}
                                <li class="list-inline-item">
                                    <a href="{{ social_media.telegram_url }}"> <img
                                            src="{{ social_media.telegram_icon.url }}" height="18px" width="18px"
                                            alt=""
                                            style="padding-bottom: 5px;">
                                    </a>
                                </li>
                            {% endif %}

                            {% if social_media.email_icon %}
                                <li class="list-inline-item">
                                    <a href="{{ social_media.email_url }}"> <img
                                            src="{{ social_media.email_icon.url }}" height="18px" width="18px"
                                            alt=""
                                            style="padding-bottom: 5px;">
                                    </a>
                                </li>
                            {% endif %}

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--footer bottom end-->
</footer>
<!--footer section end-->

templates/includes/head.html
<head>

    {% include 'includes/meta_tags.html' %}

    <!--title-->
    <title>عارضه یابی شریف</title>

    {% include 'includes/css_urls.html' %}

</head>

templates/includes/header.html
{% load static %}

<!--header start-->
<header class="main-header w-100">
    <nav class="navbar navbar-expand-xl navbar-light sticky-header">
        <div class="container d-flex align-items-center justify-content-lg-between position-relative">
            <a href="{% url 'home:home' %}" class="navbar-brand d-flex align-items-center mb-md-0 text-decoration-none">
                <img src="{% static 'img/logo-white.png' %}" alt="logo" class="img-fluid logo-white">
                <img width="80px" height="30px" src="{% static 'img/logo-dark.jpg' %}" alt="logo"
                     class="img-fluid logo-color">
            </a>

            <a class="navbar-toggler position-absolute right-0 border-0" href="#offcanvasWithBackdrop"
               role="button">
                    <span class="far fa-bars" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBackdrop"
                          aria-controls="offcanvasWithBackdrop"></span>
            </a>

            <div class="collapse navbar-collapse justify-content-center">
                <ul class="nav col-12 col-md-auto justify-content-center main-menu">
                    <li><a href="{% url 'home:home' %}" class="nav-link">خانه</a></li>
                    <li><a href="{% url 'diagnose:form' %}" class="nav-link">فرم عارضه یابی</a></li>
                    <li><a href="{% url 'weblog:all' %}" class="nav-link">وبلاگ‌ها</a></li>
                    <li><a href="{% url 'news:all' %}" class="nav-link">اخبار</a></li>
                    <li><a href="{% url 'us:about' %}" class="nav-link">درباره ما</a></li>
                    <li><a href="{% url 'us:contact' %}" class="nav-link">ارتباط با ما</a></li>
                    <li><a href="{% url 'us:faqs' %}" class="nav-link">سوالات متداول</a></li>
                </ul>
            </div>

            {% if request.user.is_authenticated %}
                <div class="action-btns text-end me-5 me-lg-0 d-none d-md-block d-lg-block">
                    <a href="{% url 'account:logout' %}" class="btn btn-danger">خروج از حساب کاربری</a>
                </div>
                {% if request.user.is_superuser %}
                    <div style="margin-right: 10px"
                         class="action-btns text-end me-5 me-lg-0 d-none d-md-block d-lg-block">
                        <a target="_blank" href="{% url 'admin:index' %}" class="btn btn-success">پنل ادمین</a>
                    </div>
                {% endif %}
            {% else %}
                <div class="action-btns text-end me-5 me-lg-0 d-none d-md-block d-lg-block">
                    <a href="{% url 'account:login' %}" class="btn btn-primary">ورود</a>
                    <a href="{% url 'account:register' %}" class="btn btn-warning">ثبت نام</a>
                </div>
            {% endif %}

            <!--offcanvas menu start-->
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasWithBackdrop">
                <div class="offcanvas-header d-flex align-items-center mt-4">
                    <a href="{% url 'home:home' %}" class="d-flex align-items-center mb-md-0 text-decoration-none">
                        <img width="80px" height="30px" src="{% static 'img/logo-dark.jpg' %}" alt="logo"
                             class="img-fluid ps-2">
                    </a>
                    <button type="button" class="close-btn text-danger" data-bs-dismiss="offcanvas"
                            aria-label="Close"><i class="far fa-close"></i></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="nav col-12 col-md-auto justify-content-center main-menu">
                        <li><a href="{% url 'home:home' %}" class="nav-link">خانه</a></li>
                        <li><a href="{% url 'diagnose:form' %}" class="nav-link">فرم عارضه یابی</a></li>
                        <li><a href="{% url 'weblog:all' %}" class="nav-link">وبلاگ‌ها</a></li>
                        <li><a href="{% url 'news:all' %}" class="nav-link">اخبار</a></li>
                        <li><a href="{% url 'us:about' %}" class="nav-link">درباره ما</a></li>
                        <li><a href="{% url 'us:contact' %}" class="nav-link">ارتباط با ما</a></li>
                        <li><a href="{% url 'us:faqs' %}" class="nav-link">سوالات متداول</a></li>

                    </ul>

                    {% if request.user.is_authenticated %}
                        <div class="action-btns mt-4 pe-3">
                            <a href="{% url 'account:logout' %}" class="btn btn-outline-danger me-2">خروج از حساب
                                کاربری</a>
                        </div>
                        {% if request.user.is_superuser %}
                            <div style="margin-right: 10px" class="action-btns mt-4 pe-3">
                                <a target="_blank" href="{% url 'admin:index' %}" class="btn btn-outline-success me-2">پنل ادمین</a>
                            </div>
                        {% endif %}
                    {% else %}
                        <div class="action-btns mt-4 pe-3">
                            <a href="{% url 'account:login' %}" class="btn btn-outline-primary me-2">ورود</a>
                        </div>
                        <div class="action-btns mt-4 pe-3">
                            <a href="{% url 'account:register' %}" class="btn btn-outline-warning me-2">ثبت نام</a>
                        </div>
                    {% endif %}

                </div>
            </div>
            <!--offcanvas menu end-->
        </div>
    </nav>
</header>
<!--header end-->

templates/includes/js_urls.html
{% load static %}

<script src="{% static 'js/sweetalert2.js' %}"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
<script src="{% static 'js/vendors/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/vendors/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/vendors/swiper-bundle.min.js' %}"></script>
<script src="{% static 'js/vendors/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/vendors/parallax.min.js' %}"></script>
<script src="{% static 'js/vendors/aos.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>

templates/includes/messages_handler.html
{% for message in messages %}
    {% if message %}
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                Swal.fire({
                    text: "{{ message }}",
                    icon: "{{ message.tags }}",
                    timer: 4000
                });
            });
        </script>
    {% endif %}
{% endfor %}

templates/includes/meta_tags.html
<!--required meta tags-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

<!--twitter og-->
<meta name="twitter:site" content="@themetags">
<meta name="twitter:creator" content="@themetags">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Quiety - Creative SAAS Technology & IT Solutions Bootstrap 5 HTML Template">
<meta name="twitter:description"
      content="Quiety creative Saas, software technology, Saas agency & business Bootstrap 5 Html template. It is best and famous software company and Saas website template.">
<meta name="twitter:image" content="#">

<!--facebook og-->
<meta property="og:url" content="#">
<meta name="twitter:title" content="Quiety - Creative SAAS Technology & IT Solutions Bootstrap 5 HTML Template">
<meta property="og:description"
      content="Quiety creative Saas, software technology, Saas agency & business Bootstrap 5 Html template. It is best and famous software company and Saas website template.">
<meta property="og:image" content="#">
<meta property="og:image:secure_url" content="#">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="600">

<!--meta-->
<meta name="description"
      content="Quiety creative Saas, software technology, Saas agency & business Bootstrap 5 Html template. It is best and famous software company and Saas website template.">
<meta name="author" content="ThemeTags">

templates/includes/preloader.html
{% load static %}

<!--preloader start-->
<div id="preloader">
    <div class="preloader-wrap">
        <img src="{% static "img/favicon.png" %}" alt="logo" class="img-fluid preloader-icon">
        <div class="loading-bar"></div>
    </div>
</div>
<!--preloader end-->

templates/includes/side_bar_ad.html
<div class="col-lg-4">
    <div class="job-overview-wrap bg-light p-5 sticky-sidebar rounded-custom mt-5 mt-lg-0">
        <h5>آیا شما هم می‌خواهید شرکت خود را ارتقا دهید؟</h5>
        <a href="{% url 'diagnose:form' %}" class="btn btn-primary mt-4">ثبت فرم</a>
    </div>
</div>

templates/includes/subscription.html
<!--cat subscribe start-->
<section class="cta-subscribe bg-dark ptb-120 position-relative overflow-hidden">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="subscribe-info-wrap text-center position-relative z-2">
                    <div class="section-heading">
                        <h4 class="h5 text-warning">شنبه دیره!</h4>
                        <h2> همین امروز شرکت خود را عارضه یابی کنید. </h2>
                        <p>با آپلود یک فرم ساده، شرکت خود را بهبود ببخشید!</p>
                    </div>
                    <div class="form-block-banner mw-60 m-auto mt-5">
                        <a href="{% url 'diagnose:form' %}" class="btn btn-primary">فرم عارضه یابی</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-circle rounded-circle circle-shape-3 position-absolute bg-dark-light right-5"></div>
        <div class="bg-circle rounded-circle circle-shape-1 position-absolute bg-warning left-5"></div>
    </div>
</section>
<!--cat subscribe end-->