SharifMBI/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from SharifMBI import settings

urlpatterns = ([
                   path("", include("Home.urls")),
                   path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
                   path('ratings/', include("star_ratings.urls", namespace="ratings")),
                   path('hitcount/', include("hitcount.urls", namespace="hitcount")),
                   path("i18n/", include("django.conf.urls.i18n")),
                   path("account/", include("Account.urls")),
                   path("us/", include("Us.urls")),
                   path("weblog/", include("Weblog.urls")),
                   path("news/", include("News.urls")),
                   path("diagnose/", include("Diagnose.urls")),
               ] +
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += i18n_patterns(path("admin/", admin.site.urls))

Us/urls.py
from django.urls import path

from Us import views

app_name = 'us'

urlpatterns = [
    path('about', views.About.as_view(), name='about'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('customers', views.CustomerList.as_view(), name='customers'),
    path('customer/<slug>', views.CustomerDetail.as_view(), name='customer'),
    path('faq/detail/<slug>', views.FaqDetail.as_view(), name='faq'),
    path('faqs', views.FaqList.as_view(), name='faqs'),
]

Us/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
from django_jalali.db.models import jDateTimeField

from Account.models import CustomUser


class Message(models.Model):
    user = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE, verbose_name="کاربر", related_name='messages',
                             blank=True, null=True)

    mobile_phone = models.CharField(max_length=11, blank=True, null=True, verbose_name="شماره تلفن")

    email = models.EmailField(max_length=254, blank=True, null=True, verbose_name="آدرس ایمیل")

    full_name = models.CharField(max_length=100, blank=True, null=True, verbose_name="نام و نام خانوادگی")

    message = models.TextField(verbose_name="متن")

    created_at = jDateTimeField(auto_now_add=True)

    def __str__(self):
        if self.user:
            return f"{self.user.username}"

        else:
            sender_name = ", ".join(filter(None, [self.full_name, self.mobile_phone, self.email]))
            return f"{sender_name}" if sender_name else "ناشناس"

    class Meta:
        db_table = 'us__message'
        verbose_name = 'پیام'
        verbose_name_plural = 'پیام‌ها'


class SocialMedia(models.Model):
    phone_1 = models.CharField(max_length=11, blank=True, null=True, verbose_name='شماره تلفن اول')

    phone_2 = models.CharField(max_length=11, blank=True, null=True, verbose_name='شماره تلفن دوم')

    telegram_url = models.URLField(blank=True, null=True, verbose_name='لینک تلگرام')

    telegram_icon = models.ImageField(upload_to="Us/SocialMedia/icons", blank=True, null=True,
                                      verbose_name='آیکون تلگرام')

    email_url = models.EmailField(blank=True, null=True, verbose_name='آدرس ایمیل')

    email_icon = models.ImageField(upload_to="Us/SocialMedia/icons", blank=True, null=True,
                                   verbose_name='آیکون ایمیل')

    telegram_number = models.CharField(max_length=13, blank=True, null=True, verbose_name='شماره تلگرام')

    whats_App_url = models.URLField(blank=True, null=True, verbose_name='لینک واتس‌اپ')

    whats_App_icon = models.ImageField(upload_to="Us/SocialMedia/icons", blank=True, null=True,
                                       verbose_name='آیکون واتس‌اپ')

    whats_App_number = models.CharField(max_length=13, blank=True, null=True, verbose_name='شماره واتس اپ')

    linkedIn_url = models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')

    linkedIn_icon = models.ImageField(upload_to="Us/SocialMedia/icons", blank=True, null=True,
                                      verbose_name='آیکون لینکدین')

    pinterest_url = models.URLField(blank=True, null=True, verbose_name='لینک پینترست')

    pinterest_icon = models.ImageField(upload_to="Us/SocialMedia/icons", blank=True, null=True,
                                       verbose_name='آیکون پینترست')

    instagram_url = models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')

    instagram_icon = models.ImageField(upload_to="Us/SocialMedia/icons", blank=True, null=True,
                                       verbose_name='آیکون اینستاگرام')

    twitter_url = models.URLField(blank=True, null=True, verbose_name='لینک توییتر')

    twitter_icon = models.ImageField(upload_to="Us/SocialMedia/icons", blank=True, null=True,
                                     verbose_name='آیکون توییتر')

    facebook_url = models.URLField(blank=True, null=True, verbose_name='لینک فیس‌بوک')

    facebook_icon = models.ImageField(upload_to="Us/SocialMedia/icons", blank=True, null=True,
                                      verbose_name='آیکون فیس‌بوک')

    def __str__(self):
        return f"شبکه اجتماعی"

    class Meta:
        db_table = 'us__social_media'
        verbose_name = 'شبکه اجتماعی'
        verbose_name_plural = 'شبکه‌های اجتماعی'


class AboutUs(models.Model):
    name = models.CharField(max_length=75, verbose_name='نام')

    short_description = CKEditor5Field(config_name="extends", verbose_name="توضیح مختصر")

    what_we_do = CKEditor5Field(config_name="extends", verbose_name="چی کار می‌کنیم؟")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'us__about_us'
        verbose_name = 'درباره'
        verbose_name_plural = 'درباره ما'


class TeamMember(models.Model):
    name = models.CharField(max_length=100, verbose_name='نام')

    role = models.CharField(max_length=100, verbose_name='نقش')

    about = models.TextField(max_length=250, verbose_name='درباره')

    image = models.ImageField(upload_to="Us/TeamMembers/images", verbose_name="تصویر عضو تیم")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'us__team_member'
        verbose_name = 'عضو تیم'
        verbose_name_plural = 'اعضای تیم'


class WhatDoCustomersEarn(models.Model):
    title = models.CharField(max_length=100, verbose_name='تیتر')

    description = models.TextField(max_length=250, verbose_name='توضیحات')

    icon = models.ImageField(upload_to="Us/WhatDoCustomersEarns/icons", verbose_name="آیکون")

    class Meta:
        db_table = 'us__what_do_customers_earn'
        verbose_name = 'مشتریان چه نتیجه‌ای دریافت می‌کنند؟'
        verbose_name_plural = 'مشتریان چه نتایجی را دریافت می‌کنند؟'


class Service(models.Model):
    pass


class Customer(models.Model):
    name = models.CharField(max_length=100, verbose_name='نام شرکت')

    slug = models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')

    link = models.URLField(blank=True, null=True, verbose_name='آدرس سایت')

    description = CKEditor5Field(config_name='extends', verbose_name='توضیحات')

    icon = models.ImageField(upload_to="Us/Customer/icons", blank=True, null=True, verbose_name="آیکون")

    image = models.ImageField(upload_to="Us/Customer/images", blank=True, null=True, verbose_name="تصویر")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'us__customer'
        verbose_name = 'مشتری'
        verbose_name_plural = 'مشتریان'


class ModasOperandi(models.Model):
    title = models.CharField(max_length=100, verbose_name='تیتر')

    description = models.TextField(verbose_name='توضیحات')

    icon = models.ImageField(upload_to="Us/ModasOperandi/icons", verbose_name="آیکون")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = 'us__modas_operandi'
        verbose_name = 'روال کار'
        verbose_name_plural = 'روال‌های کار'


class Faq(models.Model):
    question = models.CharField(max_length=150, verbose_name='سوال')

    slug = models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='اسلاگ')

    answer = CKEditor5Field(config_name='extends', verbose_name='جواب')

    def __str__(self):
        return f"{self.question}"

    class Meta:
        db_table = 'us__faq'
        verbose_name = 'سوال متداول'
        verbose_name_plural = 'سوالات متداول'

Us/forms.py
from django.forms import ModelForm, forms

from Us.models import Message

from django import forms


class ContactForm(forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ContactForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        mobile_phone = cleaned_data.get('mobile_phone')

        if not self.request.user.is_authenticated and not (email or mobile_phone):
            raise forms.ValidationError("لطفا حداقل یکی از فیلد‌های شماره تلفن یا آدرس ایمیل را پر کنید.")

        return cleaned_data

Us/views.py
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404
from django.utils.encoding import uri_to_iri
from django.views.generic import TemplateView, FormView, ListView, DetailView

from Account.models import CustomUser
from Home.mixins import URLStorageMixin
from Us.forms import ContactForm
from Us.models import AboutUs, Customer, Faq


class About(URLStorageMixin, TemplateView):
    template_name = "Us/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        about = AboutUs.objects.last()

        context['about'] = about

        return context


class Contact(URLStorageMixin, FormView):
    form_class = ContactForm
    template_name = "Us/contact.html"
    success_url = "/"

    def get_form_kwargs(self):
        kwargs = super(Contact, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        message = form.cleaned_data.get("message")

        if self.request.user.is_authenticated:
            user = CustomUser.objects.get(username=self.request.user.username)
            mobile_phone = form.cleaned_data.get("mobile_phone", user.mobile_phone)
            email = form.cleaned_data.get("email", user.email)
            full_name = form.cleaned_data.get("full_name", user.full_name)

            if mobile_phone is None:
                mobile_phone = user.mobile_phone

            if email is None:
                email = user.email

            if full_name is None:
                full_name = user.full_name

            instance = form.save(commit=False)

            instance.user = user
            instance.mobile_phone = mobile_phone
            instance.email = email
            instance.full_name = full_name

            instance.save()

        else:
            mobile_phone = form.cleaned_data.get("mobile_phone")
            email = form.cleaned_data.get("email")
            full_name = form.cleaned_data.get("full_name")

            form.instance.mobile_phone = mobile_phone
            form.instance.email = email
            form.instance.full_name = full_name
            form.instance.message = message

            form.save()

        messages.success(self.request, "پیام شما با موقیت ثبت شد.")

        return redirect("us:contact")


class CustomerList(URLStorageMixin, ListView):
    model = Customer
    context_object_name = "customers"
    template_name = "Us/customers.html"


class CustomerDetail(URLStorageMixin, DetailView):
    model = Customer
    context_object_name = "customer"
    template_name = "Us/customer.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        current_customer = self.get_object()

        customers = Customer.objects.exclude(pk=current_customer.pk)

        context['customers'] = customers

        return context


class FaqList(URLStorageMixin, ListView):
    model = Faq
    context_object_name = "faqs"
    template_name = "Us/faqs.html"


class FaqDetail(URLStorageMixin, DetailView):
    model = Faq
    context_object_name = "faq"
    template_name = "Us/faq.html"

    def get_object(self, queryset=None):
        slug = uri_to_iri(self.kwargs.get(self.slug_url_kwarg))
        queryset = self.get_queryset()
        return get_object_or_404(queryset, **{self.slug_field: slug})

Us/templates/Us/about.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <!--main content wrapper start-->
    <div class="main-wrapper">

    {% include 'includes/header.html' %}

        <!--about header section start-->
        <section class="about-header-section ptb-120 position-relative overflow-hidden bg-dark"
                 style="background: url('assets/img/page-header-bg.svg')no-repeat center right">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-heading-wrap d-flex justify-content-between z-5 position-relative">
                            <div class="about-content-left">
                                <div class="about-info mb-5">
                                    <h1 class="fw-bold display-5">{{ about.name }}</h1>
                                    <p class="lead">{{ about.short_description|safe }}</p>
                                </div>
                                <img src="{% static "img/about-img-1.jpg" %}" alt="about"
                                     class="img-fluid about-img-first mt-5 rounded-custom shadow">
                            </div>
                            <div class="about-content-right">
                                <img src="{% static "img/about-img-1.jpg" %}" alt="about"
                                     class="img-fluid mb-5 rounded-custom shadow">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bg-white position-absolute bottom-0 h-25 bottom-0 left-0 right-0 z-2 py-5">
            </div>
        </section>
        <!--about header section end-->

        <section class="our-story-section pt-60 pb-120"
                 style="background: url('assets/img/shape/dot-dot-wave-shape.svg')no-repeat left bottom">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5 col-md-12 order-lg-1">
                        <div class="section-heading sticky-sidebar">
                            <h4 class="h5 text-primary">درباره ما</h4>
                            <h2> تیم عارضخ یابی شریف چه کار‌هایی انجام می‌دهد؟ </h2>
                            {{ about.what_we_do|safe }}
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--our story section end-->

        {% include 'includes/subscription.html' %}

        {% include 'includes/footer.html' %}

    </div>
    <!--main content wrapper end-->
{% endblock %}

Us/templates/Us/customer.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--main content wrapper start-->
    <div class="main-wrapper">
        {% include 'includes/header.html' %}
        <!--integration details section start-->
        <section class="integration-details ptb-120">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-lg-8 pe-5">
                        <div class="integration-details-wrap">
                            <h2> جزئیات {{ customer.name }} </h2>

                            {% if customer.image %}
                                <img src="{{ customer.image.url }}" class="img-fluid mt-4 rounded-custom"
                                     alt="مشتری عارضه یابی شریف">
                            {% endif %}

                            {{ customer.description|safe }}

                            <blockquote
                                    class="bg-white custom-shadow p-5 mt-5 rounded-custom border-4 border-primary border-top">
                                <p class="text-muted"><i class="fas fa-quote-left me-2 text-primary"></i> در سراسر جهان
                                    طرح
                                    های بلندمدت بالا در سراسر جهان با تجارت الکترونیک متمایز
                                    زیرساخت های متقاطع رسانه ای به جای اخلاق. به طور قابل اعتماد تجسم روش های آزمون
                                    متمایز
                                    بدون پایان دادن به پایان.به طور یکپارچه جوامع متقاطع پلت فرم با بازارهای باطن.به طور
                                    خلاصه خدمات کسب و کار را از طریق راه حل های قوی استفاده کنید.به طرز وحشیانه ای
                                    زیرساخت
                                    های متقابل را به جای معیارهای دقیق ارائه می دهند.
                                    <i class="fas fa-quote-right ms-2 text-primary"></i>
                                </p>
                            </blockquote>
                        </div>
                    </div>
                    {% include 'includes/side_bar_ad.html' %}
                </div>
            </div>
        </section>
        <!--integration details section end-->

        <!--related integration start-->
        <section class="related-integration ptb-120 bg-light">
            <div class="container">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-5 col-md-12">
                        <div class="section-heading">
                            <h4 class="h5 text-primary">مشتریات</h4>
                            <h2>از سایر مشتریان سایت ما دیدن کنید.</h2>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-12">
                        <div class="text-lg-start mb-4 mb-xl-0 mb-lg-0">
                            <a href="{% url 'us:customers' %}" class="btn btn-primary">مشاهده همه مشتریان</a>
                        </div>
                    </div>
                </div>
                <div class="row">

                    {% for customer in customers %}
                        <div class="col-lg-4 col-md-6">
                            <a href="{% url 'us:customer' customer.slug %}"
                               class="position-relative text-decoration-none connected-app-single bg-white border border-2 promo-border-hover bg-white mt-4 mt-xl-0 mt-lg-0 transition-base rounded-custom d-block overflow-hidden p-5">
                                <div class="position-relative connected-app-content">
                                    <div class="integration-logo bg-white rounded-circle shadow-lg p-2 d-inline-block">
                                        <img src="{{ customer.icon.url }}" width="40" alt="integration"
                                             class="img-fluid">
                                    </div>
                                    <h5>{{ customer.name }}</h5>
                                    <p class="mb-0 text-muted">{{ customer.description|safe|truncatechars:150 }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </section>
        <!--related integration end-->

        {% include 'includes/subscription.html' %}

        {% include 'includes/footer.html' %}

    </div>
    <!--main content wrapper ends-->

{% endblock %}

Us/templates/Us/customers.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <!--main content wrapper start-->
    <div class="main-wrapper">
        {% include 'includes/header.html' %}
        <!--page header section start-->
        <section class="page-header position-relative overflow-hidden ptb-120 bg-dark"
                 style="background: url('assets/img/page-header-bg.svg')no-repeat bottom right">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12">
                        <h1 class="display-5 fw-bold">لیست مشتریان سایت عارضه یابی شریف</h1>
                        <p class="lead">با مطالعه وضعیت مشتریان ما، با دید بیشتری اقدام به عارضه یابی شرکت خود کنید.</p>
                    </div>
                </div>
                <div class="bg-circle rounded-circle circle-shape-3 position-absolute bg-dark-light left-5"></div>
            </div>
        </section>
        <!--page header section end-->

        <!--integration section start-->
        <section class="our-integration ptb-120 bg-light">
            <div class="container">
                <div class="position-relative w-100">
                    <div class="row">

                        {% for customer in customers %}
                            <div class="col-lg-4 col-md-6">
                                <a href="{% url 'us:customer' customer.slug %}"
                                   class="position-relative text-decoration-none connected-app-single bg-white border border-2 bg-white mt-4 transition-base rounded-custom d-block overflow-hidden p-5">
                                    <div class="position-relative connected-app-content">
                                        <div class="integration-logo bg-white rounded-circle p-2 d-inline-block">
                                            {% if customer.icon %}
                                                <img src="{{ customer.icon.url }}" width="40" alt="integration"
                                                     class="img-fluid">
                                            {% else %}
                                                <img src="{% static 'img/no_icon.png' %}" width="40" alt="integration"
                                                     class="img-fluid">
                                            {% endif %}
                                        </div>
                                        <h5>{{ customer.name }}</h5>
                                        <p class="mb-0 text-muted">{{ customer.description|safe|truncatechars:150 }}</p>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </section>
        <!--integration section end-->

        {% include 'includes/footer.html' %}

    </div>
    <!--main content wrapper end-->

{% endblock %}

Us/templates/Us/faq.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--main content wrapper start-->
    <div class="main-wrapper">

        {% include 'includes/header.html' %}

        <!--support content section start-->
        <section class="support-content ptb-120">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-lg-8 col-md-8 p-lg-5">
                        <div class="support-article-wrap">
                            <h1 class="display-5 mb-4 fw-bold">{{ faq.question }}</h1>
                            {{ faq.answer|safe }}
                        </div>
                    </div>
                    {% include 'includes/side_bar_ad.html' %}

                </div>
            </div>
        </section>
        <!--support content section end-->

        {% include 'includes/footer.html' %}

    </div>
    <!--main content wrapper end-->
{% endblock %}

Us/templates/Us/faqs.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--main content wrapper start-->
    <div class="main-wrapper">
        <!--page header section start-->

        {% include 'includes/header.html' %}

        <section class="page-header position-relative overflow-hidden ptb-120 bg-dark"
                 style="background: url('assets/img/page-header-bg.svg')no-repeat bottom right">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-md-12">
                        <div class="text-center">
                            <h1 class="display-5 fw-bold">سوالات متداول</h1>
                            <p class="lead">در این بخش، برخی از سوالات متداولی که مشتریان از ما دارند را پاسخ دادیم تا
                                با خیال راحت با روال کار ما آشنا شوید.</p>
                        </div>
                    </div>
                </div>
                <div class="bg-circle rounded-circle circle-shape-3 position-absolute bg-dark-light left-5"></div>
            </div>
        </section>
        <!--page header section end-->


        <!--support content section start-->
        <section class="support-content ptb-120">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7 col-md-8">
                        <div class="tab-content" id="v-pills-supportContent">
                            <div class="tab-pane fade show active" id="support-tab-1" role="tabpanel">
                                <div class="support-article-wrap">
                                    <h2>سوالات متداول عارضه یابی شریف</h2>
                                    <ul class="support-article-list list-unstyled mt-4">

                                        {% for faq in faqs %}
                                            <li class="py-4 mt-2 border-light bg-light p-5 rounded-custom">
                                                <a href="{% url 'us:faq' faq.slug %}"
                                                   class="text-decoration-none d-block text-muted">
                                                    <h3 class="h5 support-article-title">{{ faq.question }}</h3>
                                                    <p>{{ faq.answer|safe|truncatechars:150 }}</p>
                                                    <span class="btn-link text-decoration-none read-more-link">ادامه مطلب<i
                                                            class="far fa-arrow-left ms-2"></i></span>
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--support content section end-->

        {% include 'includes/footer.html' %}

    </div>
    <!--main content wrapper end-->
{% endblock %}